[supabase]
url = "https://nljvyzdkeqdnaaducqsu.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sanZ5emRrZXFkbmFhZHVjcXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzg0MTgsImV4cCI6MjA2NDk1NDQxOH0.upMwWKJ4ikSms2COVWZSmOUT9eR0oyE5YsU-ZAf6-_k"